[answered]
color = "0ee2b6"
description = "Automatically closes as answered after a delay"
name = "answered"

[breaking]
color = "ffcc00"
description = "Breaking change."
name = "breaking"

[bug]
color = "d73a4a"
description = "Something isn't working"
name = "bug"

[dependencies]
color = "0366d6"
description = "Pull requests that update a dependency file"
name = "dependencies"

[discussion]
color = "c2e0c6"
description = "Some discussion around the project"
name = "discussion"

[documentation]
color = "1bc4a5"
description = "Improvements or additions to documentation"
name = "documentation"

[duplicate]
color = "cfd3d7"
description = "This issue or pull request already exists"
name = "duplicate"

[enhancement]
color = "a2eeef"
description = "New feature or request"
name = "enhancement"

[github_actions]
color = "000000"
description = "Update of github actions"
name = "github_actions"

["good first issue"]
color = "7057ff"
description = "Good for newcomers"
name = "good first issue"

[hacktoberfest]
color = "ffa663"
description = "Good issues for Hacktoberfest"
name = "hacktoberfest"

["help wanted"]
color = "008672"
description = "Extra attention is needed"
name = "help wanted"

[invalid]
color = "e4e669"
description = "This doesn't seem right"
name = "invalid"

[nochangelog]
color = "555555"
description = "Exclude pull requests from changelog"
name = "nochangelog"

[question]
color = "d876e3"
description = "Further information is requested"
name = "question"

[removed]
color = "e99695"
description = "Removed piece of functionalities."
name = "removed"

[tests]
color = "bfd4f2"
description = "CI, CD and testing related changes"
name = "tests"

[waiting]
color = "5f7972"
description = "Automatically closes if no answer after a delay"
name = "waiting"

[fund]
color = "0E8A16"
description = "Add a section linking to polar.sh for funding the issue."
name = "fund"
