# Changes here will be overwritten by Copier
_commit: 38f646a
_src_path: gh:browniebroke/pypackage-template
cli_name: aiohomeconnect
copyright_year: '2026'
documentation: true
email: marhje52@gmail.com
full_name: Martin Hjelmare
github_username: MartinHjelmare
has_cli: true
initial_commit: false
is_django_package: false
open_source_license: Apache-2.0
open_with_editor: false
package_name: aiohomeconnect
project_name: aiohomeconnect
project_short_description: An asyncio client for the Home Connect API.
project_slug: aiohomeconnect
run_uv_sync: false
setup_github: false
setup_pre_commit: false

